name:                QML
version:             0.1.0
github:              "NicklasBoto/QML"
license:             GPL-3
author:              "Nicklas Botö"
maintainer:          "git@nicbot.xyz"
copyright:           "2021 Nicklas Botö"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/NicklasBoto/QML#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- containers

library:
  source-dirs: src

executables:
  qmli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QML

tests:
  QML-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QML
